// apps/dashboard/src/components/table-row/TableRow.tsx
import { JSX } from "solid-js";
import "./table-row.scss";

interface TableRowProps {
  children: JSX.Element;
  isHeader?: boolean;
}

export function TableRow(props: TableRowProps) {
  return (
    <div class={`dm-table-row ${props.isHeader ? "dm-table-row--header" : "dm-table-row--data"}`}>
      {props.children}
    </div>
  );
}

// apps/dashboard/src/lib/components/table-row/TableRow.svelte
<script lang="ts">
	import './TableRow.scss';
	import type { Snippet } from 'svelte';

	interface Props {
		isHeader?: boolean;
		children?: Snippet;
	}

	let { isHeader = false, children }: Props = $props();
</script>

<div class="dm-table-row {isHeader ? 'dm-table-row--header' : 'dm-table-row--data'}">
	{@render children?.()}
</div>
