// apps/dashboard/src/components/alert/Alert.tsx
import { JSX } from "solid-js";
import "./Alert.scss";

interface AlertProps extends JSX.HTMLAttributes<HTMLDivElement> {
  variant?: "default" | "danger" | "success" | "warning";
  title?: string;
  icon?: JSX.Element;
}

export function Alert(props: AlertProps) {
  const variant = props.variant || "default";
  
  return (
    <div
      {...props}
      class={`dm-alert dm-alert--${variant} ${props.class || ""}`}
      role="alert"
    >
      {props.icon && <div class="dm-alert__icon">{props.icon}</div>}
      <div class="dm-alert__content">
        {props.title && <h5 class="dm-alert__title">{props.title}</h5>}
        <div class="dm-alert__description">{props.children}</div>
      </div>
    </div>
  );
}

// apps/dashboard/src/lib/components/alert/Alert.svelte
<script lang="ts">
	import './Alert.scss';
	import type { Snippet } from 'svelte';
	import type { HTMLAttributes } from 'svelte/elements';

	interface Props extends HTMLAttributes<HTMLDivElement> {
		variant?: 'default' | 'danger' | 'success' | 'warning';
		title?: string;
		icon?: Snippet;
		class?: string;
		children?: Snippet;
	}

	let {
		variant = 'default',
		title,
		icon,
		class: className = '',
		children,
		...rest
	}: Props = $props();
</script>

<div class="dm-alert dm-alert--{variant} {className}" role="alert" {...rest}>
	{#if icon}
		<div class="dm-alert__icon">{@render icon()}</div>
	{/if}
	<div class="dm-alert__content">
		{#if title}
			<h5 class="dm-alert__title">{title}</h5>
		{/if}
		<div class="dm-alert__description">
			{@render children?.()}
		</div>
	</div>
</div>
