// apps/dashboard/src/components/stack/Stack.tsx
import { JSX } from "solid-js";
import "./stack.scss";

interface StackProps {
  children: JSX.Element;
  space?: "1" | "2" | "3" | "4" | "5" | "6" | "8";
}

export function Stack(props: StackProps) {
  return (
    <div class={`dm-stack dm-stack--space-${props.space ?? "3"}`}>
      {props.children}
    </div>
  );
}

// apps/dashboard/src/lib/components/stack/Stack.svelte
<script lang="ts">
	import './Stack.scss';
	import type { Snippet } from 'svelte';

	interface Props {
		space?: '1' | '2' | '3' | '4' | '5' | '6' | '8';
		children?: Snippet;
	}

	let { space = '3', children }: Props = $props();
</script>

<div class="dm-stack dm-stack--space-{space}">
	{@render children?.()}
</div>
