// apps/dashboard/src/components/badge/Badge.tsx
import { JSX } from "solid-js";
import "./Badge.scss";

interface BadgeProps extends JSX.HTMLAttributes<HTMLDivElement> {
  variant?: "default" | "primary" | "secondary" | "danger" | "success" | "warning";
}

export function Badge(props: BadgeProps) {
  const variant = props.variant || "default";
  
  return (
    <div
      {...props}
      class={`dm-badge dm-badge--${variant} ${props.class || ""}`}
    >
      {props.children}
    </div>
  );
}

// apps/dashboard/src/lib/components/badge/Badge.svelte
<script lang="ts">
	import './Badge.scss';
	import type { Snippet } from 'svelte';
	import type { HTMLAttributes } from 'svelte/elements';

	interface Props extends HTMLAttributes<HTMLDivElement> {
		variant?: 'default' | 'primary' | 'secondary' | 'danger' | 'success' | 'warning';
		class?: string;
		children?: Snippet;
	}

	let { variant = 'default', class: className = '', children, ...rest }: Props = $props();
</script>

<div class="dm-badge dm-badge--{variant} {className}" {...rest}>
	{@render children?.()}
</div>
