// apps/dashboard/src/components/text-input/TextInput.tsx
import { JSX } from "solid-js";
import "./text-input.scss";

interface TextInputProps extends JSX.InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
  helperText?: string;
  icon?: JSX.Element;
}

export function TextInput(props: TextInputProps) {
  return (
    <div class="dm-text-input">
      {props.label && <label class="dm-text-input__label" for={props.id}>{props.label}</label>}
      <div class="dm-text-input__wrapper">
        {props.icon && <div class="dm-text-input__icon">{props.icon}</div>}
        <input 
          {...props} 
          class={`dm-text-input__field ${props.icon ? 'dm-text-input__field--with-icon' : ''} ${props.error ? 'dm-text-input__field--error' : ''} ${props.class || ""}`} 
        />
      </div>
      {(props.error || props.helperText) && (
        <span class={`dm-text-input__helper ${props.error ? 'dm-text-input__helper--error' : ''}`}>
          {props.error || props.helperText}
        </span>
      )}
    </div>
  );
}

// apps/dashboard/src/lib/components/text-input/TextInput.svelte
<script lang="ts">
	import './TextInput.scss';
	import type { Snippet } from 'svelte';
	import type { HTMLInputAttributes } from 'svelte/elements';

	interface Props extends HTMLInputAttributes {
		label?: string;
		error?: string;
		helperText?: string;
		icon?: Snippet;
		class?: string;
	}

	let {
		label,
		error,
		helperText,
		icon,
		class: className = '',
		id,
		...rest
	}: Props = $props();
</script>

<div class="dm-text-input">
	{#if label}
		<label class="dm-text-input__label" for={id}>{label}</label>
	{/if}
	<div class="dm-text-input__wrapper">
		{#if icon}
			<div class="dm-text-input__icon">{@render icon()}</div>
		{/if}
		<input
			{id}
			class="dm-text-input__field {icon ? 'dm-text-input__field--with-icon' : ''} {error
				? 'dm-text-input__field--error'
				: ''} {className}"
			{...rest}
		/>
	</div>
	{#if error || helperText}
		<span class="dm-text-input__helper {error ? 'dm-text-input__helper--error' : ''}">
			{error || helperText}
		</span>
	{/if}
</div>
