// apps/dashboard/src/lib/components/switch/Switch.svelte
<script lang="ts">
	import './Switch.scss';
	import type { HTMLInputAttributes } from 'svelte/elements';

	interface Props extends Omit<HTMLInputAttributes, 'type'> {
		label?: string;
		class?: string;
	}

	let { label, class: className = '', ...rest }: Props = $props();
</script>

<label class="dm-switch-wrapper {className}">
	<div class="dm-switch">
		<input type="checkbox" class="dm-switch__input" {...rest} />
		<span class="dm-switch__slider"></span>
	</div>
	{#if label}
		<span class="dm-switch__label">{label}</span>
	{/if}
</label>

// apps/dashboard/src/components/switch/Switch.tsx
import { JSX } from "solid-js";
import "./Switch.scss";

interface SwitchProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, "type"> {
  label?: string;
}

export function Switch(props: SwitchProps) {
  // Extract label and class, pass the rest to the input
  const { label, class: className, ...rest } = props;

  return (
    <label class={`dm-switch-wrapper ${className || ""}`}>
      <div class="dm-switch">
        <input type="checkbox" class="dm-switch__input" {...rest} />
        <span class="dm-switch__slider"></span>
      </div>
      {label && <span class="dm-switch__label">{label}</span>}
    </label>
  );
}
