// apps/dashboard/src/lib/components/button/Button.svelte
<script lang="ts">
	import './Button.scss';
	import type { Snippet } from 'svelte';
	import type { HTMLButtonAttributes } from 'svelte/elements';

	type Variant = 'primary' | 'secondary' | 'tertiary' | 'outline' | 'ghost' | 'danger';
	type Size = 'sm' | 'md' | 'lg' | 'icon';

	interface Props extends HTMLButtonAttributes {
		variant?: Variant;
		size?: Size;
		class?: string;
		children?: Snippet;
	}

	let {
		variant = 'primary',
		size = 'md',
		class: className = '',
		children,
		...rest
	}: Props = $props();
</script>

<button class="dm-button dm-button--{variant} dm-button--{size} {className}" {...rest}>
	{@render children?.()}
</button>

// apps/dashboard/src/components/button/Button.tsx
import { JSX } from "solid-js";
import "./button.scss";

interface ButtonProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary" | "tertiary" | "outline" | "ghost" | "danger";
  size?: "sm" | "md" | "lg" | "icon";
}

export function Button(props: ButtonProps) {
  const variant = props.variant || "primary";
  const size = props.size || "md";
  
  return (
    <button
      {...props}
      class={`dm-button dm-button--${variant} dm-button--${size} ${props.class || ""}`}
    >
      {props.children}
    </button>
  );
}
